[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/password"
  to = "/.netlify/functions/password"
  status = 200

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/status"
  status = 200
